# Generated by Django 5.2.7 on 2025-10-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('password_hash', models.CharField(max_length=30, verbose_name='password')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
                ('role', models.CharField(default='admin', max_length=20, verbose_name='role')),
            ],
        ),
    ]
