# Generated by Django 5.2.7 on 2025-11-22 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSurvey', '0005_question_multiplechoiceoption_enumerationanswer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(choices=[('code_snippet', 'Code Snippet'), ('image', 'Image')], max_length=20)),
                ('content', models.TextField()),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_items', to='WebSurvey.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
