# Generated by Django 5.2.6 on 2025-11-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSurvey', '0005_question_multiplechoiceoption_enumerationanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='When survey closes', null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='When survey becomes available', null=True),
        ),
    ]
