# Generated by Django 5.2.6 on 2025-11-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSurvey', '0006_survey_end_date_survey_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='assigned_sections',
            field=models.ManyToManyField(blank=True, help_text='Sections that can view this survey', related_name='assigned_surveys', to='WebSurvey.section'),
        ),
    ]
