# Generated by Django 5.2.7 on 2025-11-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSurvey', '0006_questioncontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('likert', 'Likert Scale'), ('true_false', 'True or False'), ('essay', 'Short Text'), ('enumeration', 'Enumeration'), ('heading', 'Heading'), ('subheading', 'Subheading'), ('paragraph', 'Paragraph')], max_length=20),
        ),
    ]
